### ISSUE TITLE
Updating from 1.1.0 to 1.2.0 breaks

### ISSUE THREAD

**Issue by SElab2019** [aws/aws-lambda-java-libs#105]
When I try to upgrade aws-lambda-java-core from 1.1.0 to 1.2.0. The following code breaks.
```
public class Demo implements LambdaLogger {

    @Override
    public void log(String message) {
        System.err.println(message);
    }
}

```

The code should pass, but it throws an error:
```
Demo.java:[5,7] error: Demo is not abstract and does not override abstract method log(byte[]) in LambdaLogger
```

**Comment by mukhtar** [comment]
Yes, unfortunately there was a breaking change introduced in https://github.com/aws/aws-lambda-java-libs/commit/36747fc8f24e257c31fc722a0ab5c698aa15553d#diff-6177ecfdeeafb7048b390dddea491f16 that causes this break over 2 years ago. Going forward, we'll try to make sure any breaking changes also result in a major version bump.

**Comment by SElab2019** [comment]
Hi @mukhtar , thanks for your help. It could solve my issue. BTW, would it be better to add a breaking announcement in the release note? Then all other developers who use aws-lambda-java-core can know it.
